### ISSUE TITLE
MasonryMonth doesn't put expense in the right month.

### ISSUE THREAD

**Issue by Wong-Jeremy** [tomginsberg/xpnz3#46]
See image below.

<img src="https://uploads.linear.app/faa1cd02-d863-4c49-92d4-0debe23f6787/bc8171b2-ad43-41f5-8167-8e02da3d3137/53d56a9d-0649-4f73-a651-6f5cbd0c471e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZhYTFjZDAyLWQ4NjMtNGM0OS05MmQ0LTBkZWJlMjNmNjc4Ny9iYzgxNzFiMi1hZDQzLTQxZjUtODE2Ny04ZTAyZGEzZDMxMzcvNTNkNTZhOWQtMDY0OS00ZjczLWE2NTEtNmY1Y2JkMGM0NzFlIiwiaWF0IjoxNzMxNTMwNDc2LCJleHAiOjMzMzAyMDkwNDc2fQ.xyYBwP7loHtUllelO2E2RPa_w1aqHyJXHiG9dnrh_s4 " alt="Screenshot 2024-11-13 at 12.39.30 PM.png" width="1512" height="825" />

**Comment by doms3** [comment]
I think this related to [XPN-68](https://linear.app/xpnz/issue/XPN-68/audit-all-usage-of-tolocalestring)
